modules:
  - name: KickSampler
    class: octavox.modules.sampler.SVSampler
  - name: SnareSampler
    class: octavox.modules.sampler.SVSampler
  - name: HatSampler
    class: octavox.modules.sampler.SVSampler
  - name: Echo
    class: rv.modules.echo.Echo
    defaults:
      dry: 256
      wet: 256
      delay: 192
  - name: Distortion
    class: rv.modules.distortion.Distortion
    defaults:
      power: 64
  - name: Reverb
    class: rv.modules.reverb.Reverb
    defaults:
      wet: 4
links:
  - - KickSampler
    - Echo
  - - SnareSampler
    - Echo
  - - HatSampler
    - Echo
  - - Echo
    - Distortion
  - - Distortion
    - Reverb
  - - Reverb
    - Output
sequencers:
  - name: KickSampler
    tag: kk
    styles:
    - fourfloor
    - electro
    - triplets
  - name: SnareSampler
    tag: sn
    styles:
    - backbeat
    - skip
  - name: HatSampler
    tag: ht
    styles:
    - offbeats
    - closed
lfos:
  - name: Echo/wet
    range: [0, 1]
    increment: 0.25
    step: 4
    live: 0.66666
    multiplier: 32768
  - name: Echo/feedback
    range: [0, 1]
    increment: 0.25
    step: 4
    live: 1.0
    multiplier: 32768
