ht:
- - default.zip
  - 27. Buchla TOM.wav
- - default.zip
  - 39. Buchla CB.wav
- - default.zip
  - 41. 8008 CH.wav
- - default.zip
  - 42. 9009 CH.wav
- - default.zip
  - 46. 8008 OH.wav
- - default.zip
  - 47. 9009 OH.wav
- - default.zip
  - 59. RAITIS CHRD 1.wav
- - default.zip
  - 61. RAITIS CHRD 2.wav
- - pitch-black.zip
  - 514 - zap noise culture vulture print (percussion).wav
- - pitch-black.zip
  - '"15 - Buchla bongo (percussion).wav'
- - pitch-black.zip
  - '"16 - Buchla congo (percussion).wav'
- - pitch-black.zip
  - $17 - Buchla Pop hit (percussion).wav
- - pitch-black.zip
  - '&18 - buchla tamborine (percussion).wav'
- - pitch-black.zip
  - (19 - Voyager bleep blip (percussion).wav
- - pitch-black.zip
  - 720 - Verbos complex Resonating tom hit (percussion).wav
- - pitch-black.zip
  - '&21 - swarmatron congo (percussion).wav'
- - pitch-black.zip
  - .22 - swarmatron cluster shot (percussion) .wav
- - pitch-black.zip
  - 135 - slow attack Buchla pulse trigger (tonal).wav
- - pitch-black.zip
  - 39 - buchla static (tonal).wav
- - pitch-black.zip
  - (40 - Buchla Spring verb bend (tonal).wav
- - pitch-black.zip
  - 342 - verbos harmonic oscillator chorded (drone).wav
- - pitch-black.zip
  - '!46 - buchla modulated (drone).wav'
- - pitch-black.zip
  - /47 - Buchla am mod drone w.spr-verb (drone).wav
- - pitch-black.zip
  - 48 - buchla Alarm High (fx).wav
- - pitch-black.zip
  - 49 - choir Impact (fx).wav
- - pitch-black.zip
  - $61 - buchla power on (ear candy).wav
- - pitch-black.zip
  - '*62 - buchla modulation lfo (ear candy).wav'
- - complex-waveforms.zip
  - 30 Glitch.wav
- - complex-waveforms.zip
  - 31 Glitch.wav
- - complex-waveforms.zip
  - 32 Glitch.wav
- - complex-waveforms.zip
  - 33 Glitch.wav
- - complex-waveforms.zip
  - 34 Glitch.wav
- - complex-waveforms.zip
  - 35 Glitch.wav
- - complex-waveforms.zip
  - 36 Glitch.wav
- - complex-waveforms.zip
  - 37 Glitch.wav
- - complex-waveforms.zip
  - 38 Glitch.wav
- - complex-waveforms.zip
  - 39 Glitch.wav
- - complex-waveforms.zip
  - 40 Glitch.wav
- - complex-waveforms.zip
  - 41 Glitch.wav
- - complex-waveforms.zip
  - 42 Glitch.wav
- - complex-waveforms.zip
  - 43 Glitch.wav
- - complex-waveforms.zip
  - 44 Glitch.wav
- - complex-waveforms.zip
  - 45 Glitch.wav
- - complex-waveforms.zip
  - 46 Glitch.wav
- - complex-waveforms.zip
  - 47 Glitch.wav
- - complex-waveforms.zip
  - 48 Glitch.wav
- - complex-waveforms.zip
  - 49 Glitch.wav
- - complex-waveforms.zip
  - 50 Glitch.wav
- - complex-waveforms.zip
  - 51 glitch.wav
- - complex-waveforms.zip
  - 52 Glitch.wav
- - complex-waveforms.zip
  - 53 Glitch.wav
- - complex-waveforms.zip
  - 54 Glitch.wav
- - complex-waveforms.zip
  - 55 Glitch.wav
- - complex-waveforms.zip
  - 56 Perc.wav
- - complex-waveforms.zip
  - 57 Perc.wav
- - complex-waveforms.zip
  - 58 Perc.wav
- - complex-waveforms.zip
  - 59 Perc.wav
- - complex-waveforms.zip
  - 60 Perc.wav
- - complex-waveforms.zip
  - 61 Perc.wav
- - complex-waveforms.zip
  - 62 Perc.wav
- - complex-waveforms.zip
  - 63 Perc.wav
- - complex-waveforms.zip
  - 64 Perc.wav
- - otto-von-schirach.zip
  - crash stretch.wav
- - otto-von-schirach.zip
  - Electro Acoustic hats.wav
- - otto-von-schirach.zip
  - ElectroHat .wav
- - legowelt.zip
  - 30 - ERIKA-Winterchestra.wav
- - legowelt.zip
  - 35 ERIKA-Chord1.wav
- - legowelt.zip
  - 52 ERIKA-Mechaniek.wav
- - legowelt.zip
  - 62 ERIKA-Dadchord.wav
- - legowelt.zip
  - 64 ERIKA-SHihat.wav
- - nero-bellum.zip
  - (09 - Basimilus Sub Drop (Percussion).wav
- - nero-bellum.zip
  - 10 - DPO Drop (Percussion).wav
- - nero-bellum.zip
  - '*11 - Varishape Pulse Bomb (Percussion).wav'
- - nero-bellum.zip
  - .23 - Basimilus Filtered Hat I (Percussion).wav
- - nero-bellum.zip
  - /24 - Basimilus Filtered Hat II (Percussion).wav
- - nero-bellum.zip
  - '%25 - Basimilus Hat I (Percussion).wav'
- - nero-bellum.zip
  - '&26 - Basimilus Hat II (Percussion).wav'
- - nero-bellum.zip
  - '''27 - Basimilus Hat III (Percussion).wav'
- - nero-bellum.zip
  - 28 - Clean Hat (Percussion).wav
- - nero-bellum.zip
  - 29 - Dirty Hat (Percussion).wav
- - nero-bellum.zip
  - '&30 - Dirty Hat Closed (Percussion).wav'
- - nero-bellum.zip
  - 31 - Dope Hat (Percussion).wav
- - nero-bellum.zip
  - '!32 - Machine Hat (Percussion).wav'
- - nero-bellum.zip
  - 33 - Trip Hat (Percussion).wav
- - nero-bellum.zip
  - $34 - Dark Reactor I (Percussion).wav
- - nero-bellum.zip
  - '%35 - Dark Reactor II (Percussion).wav'
- - nero-bellum.zip
  - )36 - Defleshing Automata (Percussion).wav
- - nero-bellum.zip
  - )37 - Does It Even Matter (Percussion).wav
- - nero-bellum.zip
  - 38 - Luger P08 (Percussion).wav
- - nero-bellum.zip
  - 39 - Noise Sub (Percussion).wav
- - nero-bellum.zip
  - '&40 - Perfect Weapon I (Percussion).wav'
- - nero-bellum.zip
  - '''41 - Perfect Weapon II (Percussion).wav'
- - nero-bellum.zip
  - '!42 - Sinth Steam (Percussion).wav'
- - nero-bellum.zip
  - '#43 - Basimilus Zap (Percussion).wav'
- - nero-bellum.zip
  - '"44 - Wraith Kit I (Percussion).wav'
- - nero-bellum.zip
  - '#45 - Wraith Kit II (Percussion).wav'
- - nero-bellum.zip
  - $46 - Wraith Kit III (Percussion).wav
- - nero-bellum.zip
  - '"47 - Street Trash (Percussion).wav'
- - nero-bellum.zip
  - (60 - Nightmare in Monochrome (Candy).wav
- - nero-bellum.zip
  - 61 - Witch Maw (Candy).wav
- - dj-raitis-vinyl-cuts.zip
  - 28 PERC.wav
- - dj-raitis-vinyl-cuts.zip
  - 29 PERC.wav
- - dj-raitis-vinyl-cuts.zip
  - 30 PERC.wav
- - dj-raitis-vinyl-cuts.zip
  - 31 PERC.wav
- - dj-raitis-vinyl-cuts.zip
  - 32 PERC.wav
- - dj-raitis-vinyl-cuts.zip
  - 33 PERC.wav
- - dj-raitis-vinyl-cuts.zip
  - 34 PERC.wav
- - dj-raitis-vinyl-cuts.zip
  - 35 PERC.wav
- - clipping.zip
  - 32-ShooterChamberHit.wav
- - clipping.zip
  - 37-Story2ChamberHit.wav
- - clipping.zip
  - 39-SummertimeChild.wav
- - clipping.zip
  - 44-TrueKerchunk.wav
- - clipping.zip
  - 64-ItsClippingBitch.wav
- - syntrx.zip
  - gltchm10.wav
- - syntrx.zip
  - gltchm11.wav
- - syntrx.zip
  - gltcht1.wav
- - syntrx.zip
  - gltchm3.wav
- - syntrx.zip
  - gltchm2.wav
- - syntrx.zip
  - gltcht2.wav
- - syntrx.zip
  - gltchm1.wav
- - syntrx.zip
  - gltcht3.wav
- - syntrx.zip
  - gltcht7.wav
- - syntrx.zip
  - gltchm5.wav
- - syntrx.zip
  - gltchm4.wav
- - syntrx.zip
  - gltcht6.wav
- - syntrx.zip
  - gltcht4.wav
- - syntrx.zip
  - gltchm6.wav
- - syntrx.zip
  - gltchm7.wav
- - syntrx.zip
  - gltcht5.wav
- - syntrx.zip
  - gltcht8.wav
- - syntrx.zip
  - bsprc2.wav
- - syntrx.zip
  - gltchm9.wav
- - syntrx.zip
  - bsprc1.wav
- - syntrx.zip
  - gltchm8.wav
- - syntrx.zip
  - gltchn1.wav
- - syntrx.zip
  - gltchn3.wav
- - syntrx.zip
  - gltchn2.wav
kk:
- - default.zip
  - 01. 7007 BD.wav
- - default.zip
  - 02. 8008 BD.wav
- - default.zip
  - 03. 9009 BD.wav
- - default.zip
  - 04. Buchla BD.wav
- - default.zip
  - 05. IB BD 1.wav
- - default.zip
  - 06. IB BD 2.wav
- - default.zip
  - 07. Jungle BD.wav
- - default.zip
  - 08. 9009 BD.wav
- - default.zip
  - 09. Synth BD .wav
- - default.zip
  - 10. Synth BD 2.wav
- - pitch-black.zip
  - '"01 - 808 medium decayed (Kick).wav'
- - pitch-black.zip
  - 02 - 909 punch (kick).wav
- - pitch-black.zip
  - 03 - Buchla round (kick).wav
- - pitch-black.zip
  - 04 - dark energy (kick).wav
- - pitch-black.zip
  - 05 - doom (kick).wav
- - pitch-black.zip
  - 06 - Heavy 808 (kick).wav
- - pitch-black.zip
  - 07 - roundhouse (kick).wav
- - pitch-black.zip
  - '*08 - Verbos amp tone controller (kick).wav'
- - pitch-black.zip
  - ',24 - verbos complex saw bass shot (lead).wav'
- - pitch-black.zip
  - 328 - Ernie ball bass guitar note sustain (lead).wav
- - pitch-black.zip
  - ' 33 - buchla bass shot (lead).wav'
- - pitch-black.zip
  - '#34 - Ob-6  Saw bass Stab (lead).wav'
- - pitch-black.zip
  - 543 - grim reaper verbos harmonic osc bass (drone).wav
- - complex-waveforms.zip
  - 01 Kick.wav
- - complex-waveforms.zip
  - 02 Kick.wav
- - complex-waveforms.zip
  - 03 Kick.wav
- - complex-waveforms.zip
  - 04 Kick.wav
- - complex-waveforms.zip
  - 05 Kick.wav
- - complex-waveforms.zip
  - 06 Kick.wav
- - complex-waveforms.zip
  - 07 Kick.wav
- - complex-waveforms.zip
  - 08 Kick.wav
- - complex-waveforms.zip
  - 10 Kick.wav
- - complex-waveforms.zip
  - 11 Kick.wav
- - complex-waveforms.zip
  - 12 Kick.wav
- - complex-waveforms.zip
  - 13 Kick.wav
- - complex-waveforms.zip
  - 14 Kick.wav
- - complex-waveforms.zip
  - 15 Kick.wav
- - otto-von-schirach.zip
  - Electro kik.wav
- - otto-von-schirach.zip
  - hank kik.wav
- - otto-von-schirach.zip
  - Miami Bass 808 1.wav
- - otto-von-schirach.zip
  - Miami Bass clap.wav
- - otto-von-schirach.zip
  - Miami Bass hat.wav
- - otto-von-schirach.zip
  - Miami Bass kik.wav
- - otto-von-schirach.zip
  - Miami Bass Sd 1.wav
- - otto-von-schirach.zip
  - Miami Bass Sd 2.wav
- - otto-von-schirach.zip
  - pickle kik.wav
- - otto-von-schirach.zip
  - Static Lic kik.wav
- - otto-von-schirach.zip
  - SYNCUSSION BASS.wav
- - otto-von-schirach.zip
  - top kik.wav
- - legowelt.zip
  - 1 ERIKA-BD1.wav
- - legowelt.zip
  - 10 ERIKA-HardtechnoBD.wav
- - legowelt.zip
  - 11 ERIKA-IndustrialBassdrum.wav
- - legowelt.zip
  - 12 ERIKA-OverdriveBD.wav
- - legowelt.zip
  - 2 ERIKA-BD2.wav
- - legowelt.zip
  - 3 ERIKA-BD3.wav
- - legowelt.zip
  - 4 ERIKA-BD4.wav
- - legowelt.zip
  - 5 ERIKA-BD5.wav
- - legowelt.zip
  - 6 ERIKA-BD6.wav
- - legowelt.zip
  - 7 ERIKA-BD7.wav
- - legowelt.zip
  - 8 ERIKA-BDhat.wav
- - legowelt.zip
  - 9 ERIKA-BDlotom.wav
- - nero-bellum.zip
  - -01 - Basimilus Filtered Kick (Percussion).wav
- - nero-bellum.zip
  - '*02 - Basimilus Trash Kick (Percussion).wav'
- - nero-bellum.zip
  - '"03 - Brute Kick I (Percussion).wav'
- - nero-bellum.zip
  - '#04 - Brute Kick II (Percussion).wav'
- - nero-bellum.zip
  - 005 - Uncle Tom's Blackened Kick (Percussion).wav
- - nero-bellum.zip
  - '*06 - Prophet 12 Kick Long (Percussion).wav'
- - nero-bellum.zip
  - '&07- Grimy Gretch Kick (Percussion).wav'
- - nero-bellum.zip
  - '"08 - Pentode Kick (Percussion).wav'
- - nero-bellum.zip
  - '#53 - GR700 Shredder Bass (Bass).wav'
- - nero-bellum.zip
  - '&54 - Fuck Your Shit (Bass) 140 bpm.wav'
- - nero-bellum.zip
  - "55 - \xC6thers Tide (Bass).wav"
- - dj-raitis-vinyl-cuts.zip
  - 01 BD.wav
- - dj-raitis-vinyl-cuts.zip
  - 02 BD.wav
- - dj-raitis-vinyl-cuts.zip
  - 03 BD.wav
- - dj-raitis-vinyl-cuts.zip
  - 04 BD.wav
- - dj-raitis-vinyl-cuts.zip
  - 05 BD.wav
- - dj-raitis-vinyl-cuts.zip
  - 06 BD.wav
- - dj-raitis-vinyl-cuts.zip
  - 07 BD.wav
- - dj-raitis-vinyl-cuts.zip
  - 08 BD.wav
- - dj-raitis-vinyl-cuts.zip
  - 09 BD.wav
- - dj-raitis-vinyl-cuts.zip
  - 10 BD.wav
- - dj-raitis-vinyl-cuts.zip
  - 11 BD.wav
- - clipping.zip
  - 08-BackUpSBDrugs.wav
- - clipping.zip
  - 11-BetterPlaceKick.wav
- - clipping.zip
  - 29-ShooterKick.wav
- - clipping.zip
  - 30-ShooterKick2.wav
- - clipping.zip
  - 33-Shooter-MelodyBass.wav
- - clipping.zip
  - 42-TrueKick.wav
- - clipping.zip
  - 47-WakeUpBass.wav
- - ib-magnetic-saturation.zip
  - 01 BD.wav
- - ib-magnetic-saturation.zip
  - 02 BD.wav
- - ib-magnetic-saturation.zip
  - 03 BD.wav
- - ib-magnetic-saturation.zip
  - 04 BD.wav
- - ib-magnetic-saturation.zip
  - 05 BD.wav
- - ib-magnetic-saturation.zip
  - 06 BD.wav
- - ib-magnetic-saturation.zip
  - 07 BD.wav
- - ib-magnetic-saturation.zip
  - 08 BD.wav
- - syntrx.zip
  - bass1.wav
- - syntrx.zip
  - bass2.wav
- - syntrx.zip
  - kik3.wav
- - syntrx.zip
  - kik2.wav
- - syntrx.zip
  - kik1.wav
sn:
- - default.zip
  - 11. 7007 SD.wav
- - default.zip
  - 12. 8008 SD.wav
- - default.zip
  - 13. 9009 SD.wav
- - default.zip
  - 14. IB SD 1.wav
- - default.zip
  - 15. IB SD 2.wav
- - default.zip
  - 16. IB SD 3.wav
- - default.zip
  - 17. Synth SD 1.wav
- - default.zip
  - 18. Synth SD 2.wav
- - default.zip
  - 19. Jungle SD.wav
- - pitch-black.zip
  - '*09 - crash snare culture print (Snare).wav'
- - pitch-black.zip
  - ',10 - Culture  vulture  Pentode 2 (Snare).wav'
- - pitch-black.zip
  - 11 - noise snap (snare).wav
- - pitch-black.zip
  - 12 - ob-6 noise (snare) .wav
- - pitch-black.zip
  - (13 - Smack my pitch up stc08 (Snare).wav
- - otto-von-schirach.zip
  - Electro Acoustic sd.wav
- - otto-von-schirach.zip
  - Electro sd.wav
- - otto-von-schirach.zip
  - Gabba sd 1.wav
- - otto-von-schirach.zip
  - hank Sd 2.wav
- - otto-von-schirach.zip
  - Ring Snare.wav
- - otto-von-schirach.zip
  - Static Sd.wav
- - otto-von-schirach.zip
  - Static Snare .wav
- - otto-von-schirach.zip
  - Zort Sd .wav
- - otto-von-schirach.zip
  - Zort Sd 2.wav
- - otto-von-schirach.zip
  - Zort Sd 3.wav
- - legowelt.zip
  - 13 ERIKA-SD1.wav
- - legowelt.zip
  - 14 ERIKA-SD2.wav
- - legowelt.zip
  - 15 ERIKA-SD3.wav
- - legowelt.zip
  - 16 ERIKA-SDnoise.wav
- - legowelt.zip
  - 17 ERIKA-SDelectro.wav
- - legowelt.zip
  - 18 ERIKA-Snurrydrum.wav
- - legowelt.zip
  - 19 - ERIKA-SDxtreeeem.wav
- - legowelt.zip
  - 20 ERIKA-SDfuture.wav
- - legowelt.zip
  - 21 ERIKA-SDthunderwip.wav
- - legowelt.zip
  - 22 ERIKA-DimensionSnare.wav
- - legowelt.zip
  - 23 ERIKA-CLAP1.wav
- - legowelt.zip
  - 24 ERIKA-DuistereCLAP.wav
- - nero-bellum.zip
  - +12 - Basimilus Trash Snare (Percussion).wav
- - nero-bellum.zip
  - '#13 - Brute Snare I (Percussion).wav'
- - nero-bellum.zip
  - $14 - Brute Snare II (Percussion).wav
- - nero-bellum.zip
  - /15 - Brute Snare III Sidestick (Percussion).wav
- - nero-bellum.zip
  - $16 - Erbeverb Snare (Percussion).wav
- - nero-bellum.zip
  - '!17 - Fuego Snare (Percussion).wav'
- - nero-bellum.zip
  - '&18 - Noise Blade Snare (Percussion.wav'
- - nero-bellum.zip
  - )19 - Stacked Noise Snare (Percussion).wav
- - nero-bellum.zip
  - (20 - Warfare Snare Roll (Percussion).wav
- - nero-bellum.zip
  - ',21 - Vintage Machines Snare (Percussion).wav'
- - nero-bellum.zip
  - '#22 - Pentode Snare (Percussion).wav'
- - dj-raitis-vinyl-cuts.zip
  - 12 SD.wav
- - dj-raitis-vinyl-cuts.zip
  - 13 SD.wav
- - dj-raitis-vinyl-cuts.zip
  - 14 SD.wav
- - dj-raitis-vinyl-cuts.zip
  - 15 SD.wav
- - dj-raitis-vinyl-cuts.zip
  - 16 SD.wav
- - dj-raitis-vinyl-cuts.zip
  - 17 SD.wav
- - dj-raitis-vinyl-cuts.zip
  - 18 SD.wav
- - dj-raitis-vinyl-cuts.zip
  - 19 SD.wav
- - dj-raitis-vinyl-cuts.zip
  - 20 SD.wav
- - dj-raitis-vinyl-cuts.zip
  - 21 SD.wav
- - dj-raitis-vinyl-cuts.zip
  - 22 SD.wav
- - dj-raitis-vinyl-cuts.zip
  - 23 SD.wav
- - dj-raitis-vinyl-cuts.zip
  - 24 SD.wav
- - dj-raitis-vinyl-cuts.zip
  - 25 SD.wav
- - dj-raitis-vinyl-cuts.zip
  - 26 CP.wav
- - dj-raitis-vinyl-cuts.zip
  - 27 CP.wav
- - clipping.zip
  - 15-BreakTheGlassDoorSlam.wav
- - clipping.zip
  - 23-GetItVegBreakSnare.wav
- - clipping.zip
  - 25-HotFuckNoLove-Clap.wav
- - clipping.zip
  - 31-ShooterSnare.wav
- - clipping.zip
  - 43-TrueSnare.wav
- - ib-magnetic-saturation.zip
  - 09 SD.wav
- - ib-magnetic-saturation.zip
  - 10 SD.wav
- - ib-magnetic-saturation.zip
  - 11 SD.wav
- - ib-magnetic-saturation.zip
  - 12 SD.wav
- - ib-magnetic-saturation.zip
  - 13 SD.wav
- - ib-magnetic-saturation.zip
  - 14 SD.wav
- - ib-magnetic-saturation.zip
  - 15 SD.wav
- - ib-magnetic-saturation.zip
  - 16 SD.wav
- - ib-magnetic-saturation.zip
  - 17 SD.wav
- - ib-magnetic-saturation.zip
  - 18 SD.wav
- - ib-magnetic-saturation.zip
  - 19 SD.wav
- - ib-magnetic-saturation.zip
  - 20 SD.wav
- - ib-magnetic-saturation.zip
  - 21 SD.wav
- - ib-magnetic-saturation.zip
  - 22 SD.wav
- - ib-magnetic-saturation.zip
  - 23 SD.wav
- - ib-magnetic-saturation.zip
  - 24 SD.wav
- - ib-magnetic-saturation.zip
  - 29 CP.wav
- - syntrx.zip
  - snare1.wav
- - syntrx.zip
  - snare2.wav
- - syntrx.zip
  - snare3.wav
